spring:
  # spring data for mongodb
  data:
    mongodb:
      host: 192.168.2.88

  redis:
    host: 192.168.2.88
    password: Redis_kmzx@1234

logging:
  level:
    com:
      ynzhongxi:
        gpsreport: debug
  file: E:/develop/logs/pgs_report/log.log