spring:
  # spring data for mongodb

  data:
    mongodb:
      host: 127.0.0.1
      database: pgsReport

  redis:
    host: 127.0.0.1
    password:

logging:
  level:
    com:
      ynzhongxi:
        gpsreport: debug
  file: E:/develop/logs/pgs_report/log.log-

custom:
  gps-cms-path: D:\\WebStorm\\gps_cms


